### ISSUE TITLE
dbus: add GetValue on root item

### ISSUE THREAD

**Issue by mpvader** [mpvader/venus-signalk#8]
This must be done for all services at startup, and every time a new service is found.
Returned data must be used to make a signalk delta.

Probably with code similar to:

```
bus.invoke({
      path: '/',
      destination: name,
      interface: 'com.victronenergy.BusItem',
      member: "GetValue"
    }, function(err, res) {
```

But that results in this error. Check by using dbus-monitor while doing a `dbus com.victronenergy.battery.ttyO1 / GetValue` call how the messages on dbus differ from how above nodejs code creates them.

```ERROR:dbus.service:Unable to append (dbus.Dictionary({dbus.String(u'Dummy'): dbus.Int32(1788), dbus.String(u'HardwareVersion'): dbus.Int32(0), dbus.String(u'Capacity'): dbus.Int32(100), dbus.String(u'Level'): dbus.Int32(20), dbus.String(u'DeviceInstance'): dbus.Int32(234), dbus.String(u'Remaining'): dbus.Int32(20), dbus.String(u'ProductName'): dbus.String(u'Tank sensor'), dbus.String(u'Connected'): dbus.Int32(1), dbus.String(u'Mgmt/ProcessVersion'): dbus.String(u'Unkown version, and running on Python 2.7.3'), dbus.String(u'FluidType'): dbus.Int32(0), dbus.String(u'Mgmt/ProcessName'): dbus.String(u'./../ext/velib_python/dbusdummyservice.pyo'), dbus.String(u'Mgmt/Connection'): dbus.String(u'Dummy service'), dbus.String(u'FirmwareVersion'): dbus.Int32(0), dbus.String(u'ProductId'): dbus.Int32(0)}, signature=None),) to message with signature v: <type 'exceptions.TypeError'>: an integer is required```

**Comment by mpvader** [comment]
The problem is with dbus-recorder. Doing the `dbus .. / GetValue` request on a service created by dbus-recorder:
```
$ dbus com.victronenergy.tank.tty36 / GetValue
Traceback (most recent call last):
  File "/usr/bin/dbus", line 364, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required
```

Doing a GetValue on root request on a more normal type service:
```
$ dbus com.victronenergy.battery.ttyO1 / GetValue
{'Connected': 1,
 'Dc/0/Current': 2,
 'Dc/0/Power': 48.6,
 'Dc/0/Voltage': 24.3,
 'DeviceInstance': 0,
 'FirmwareVersion': 0,
 'HardwareVersion': 0,
 'Mgmt/Connection': 'VE.Direct port 1',
 'Mgmt/ProcessName': '/home/matthijs/dev/velib_python/dbusdummyservice.pyc',
 'Mgmt/ProcessVersion': 'Unkown version, and running on Python 2.7.12',
 'ProductId': 0,
 'ProductName': 'BMV-700',
 'Soc': 100}
```

**Comment by mpvader** [comment]
When running [this test harness](https://gist.github.com/mpvader/94672c05d68bb6762859ba70240ea887), instead of the dbus-recorder/play.sh one, it works:

```
$ ./demo.sh 
com.victronenergy.battery.ttyO1
res: [[{"type":"a","child":[{"type":"{","child":[{"type":"s","child":[]},{"type":"v","child":[]}]}]}],[[["Dc/0/Voltage",[[{"type":"d","child":[]}],[24.3]]],["Dc/0/Power",[[{"type":"d","child":[]}],[48.6]]],["HardwareVersion",[[{"type":"i","child":[]}],[0]]],["Mgmt/ProcessName",[[{"type":"s","child":[]}],["/home/matthijs/dev/velib_python/dbusdummyservice.pyc"]]],["DeviceInstance",[[{"type":"i","child":[]}],[0]]],["Soc",[[{"type":"i","child":[]}],[100]]],["ProductName",[[{"type":"s","child":[]}],["BMV-700"]]],["Connected",[[{"type":"i","child":[]}],[1]]],["Mgmt/ProcessVersion",[[{"type":"s","child":[]}],["Unkown version, and running on Python 2.7.12"]]],["Dc/0/Current",[[{"type":"i","child":[]}],[2]]],["Mgmt/Connection",[[{"type":"s","child":[]}],["VE.Direct port 1"]]],["FirmwareVersion",[[{"type":"i","child":[]}],[0]]],["ProductId",[[{"type":"i","child":[]}],[0]]]]]]
```

This leaves us with a bit of a problem: once we put the commit in venus-signalk that adds the root requests, we can no longer use the dbus-recorder test harness.
